stages:
  split:
    cmd: python src/data/split.py --raw_path data/raw/raw.csv --out_dir data/processed
    deps:
    - data/raw/raw.csv
    - src/data/split.py
    outs:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - data/processed/y_test.csv
    - data/processed/y_train.csv
  normalize:
    cmd: python src/data/normalize.py
    deps:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - src/data/normalize.py
    outs:
    - data/processed/X_test_scaled.csv
    - data/processed/X_train_scaled.csv
    - models/artefacts/pipe_scaler.pkl
  gridsearch:
    cmd: python src/models/grid_search.py
    deps:
    - data/processed/X_train_scaled.csv
    - data/processed/y_train.csv
    - src/models/grid_search.py
    outs:
    - models/artefacts/best_params.pkl
  train:
    cmd: python src/models/train.py
    deps:
    - data/processed/X_train_scaled.csv
    - data/processed/y_train.csv
    - models/artefacts/best_params.pkl
    - src/models/train.py
    outs:
    - models/gbr_model.pkl
  evaluate:
    cmd: python src/models/evaluate.py
    deps:
    - data/processed/X_test_scaled.csv
    - data/processed/y_test.csv
    - models/gbr_model.pkl
    - src/models/evaluate.py
    outs:
    - data/prediction.csv
    metrics:
    - metrics/scores.json:
        cache: false
